name: Grid data
description: File a grid format
title: "Grid Format Addition Request: "
body:
  - type: textarea
    id: grid-description
    attributes:
      label: Grid Description
      description: Describe the grid
      placeholder: Description.....
    validations:
      required: true
  - type: dropdown
    attributes: 
      label: Type
      description: What is the grid type?
      multiple: false
      options:
        - simple
        - complex
      default: 0
    validations: 
      required: true
  - type: input
    id: lat-points
    attributes:
      label: Latitude Points
      description: Number of latitude points
      placeholder: ...
    validations:
      required: true
  - type: input
    id: long-points
    attributes:
      label: Longitude Points
      description: Number of longitude points
      placeholder: ...
    validations:
      required: true



