name: Grid data
description: File a grid format
title: "[Grid]: "
body:
  - type: markdown
    attributes: 
      value: Input grid information.
  - type: textarea
    id: grid-description
    attributes:
      label: Grid description
      description: Grid description:
      placeholder: Description.....
    validations:
      required: true
  - type: dropdown
    attributes: 
      label: type
      description: What is the grid type?
      multiple: false
      options:
        - simple
        - complex
      default: 0
    validations: 
      required: true
  - type: input
    id: lat-points
    attributes:
      label: Laitude-points
      description: Number of latitude points
      placeholder: ...
    validations:
      required: true
  - type: input
    id: long-points
    attributes:
      label: Longitude-points
      description: Number of longitude points
      placeholder: ...
    validations:
      required: true



