name: 'Setup Repo'
description: 'configure user and authentication settings'
inputs:
  token:
    description: 'token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure user
      run: 
        git config --global user.name 
        git config --global user.email
      shell: bash
