name: "create pull request"
on:
  issues:
    type: opened
  workflow_dispatch:
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - uses: ./.github/actions/update-and-push
      - name: Open pull request
        run: |
          gh pr create \
            --title "New grid format added from issue form" \
            --body "New grid format added" \
            --base main \
            --head $(git rev-parse --abbrev-ref HEAD)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
