name: test-action
on: 
  issues:
    types: opened
  workflow_dispatch:
jobs:
  update_database:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: confirm action
        run: echo "action successfull"
        # run: assign file ID g<type>NNN.json
        # run: check for duplicate based on longs, lats and type, if unique, store in repo
        # run: if duplicate message user pointing them to ID 
  
